--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ciga/Pictures/desert-red-sky.png"

-- Special
background="#07060c"
foreground="#a8a6b1"
cursor="#a8a6b1"

-- Colors
color0="#07060c"
color1="#56345c"
color2="#7a2d4b"
color3="#5c4c58"
color4="#ae3c5f"
color5="#94818c"
color6="#948c94"
color7="#a8a6b1"
color8="#524d63"
color9="#56345c"
color10="#7a2d4b"
color11="#5c4c58"
color12="#ae3c5f"
color13="#94818c"
color14="#948c94"
color15="#a8a6b1"
