# Shell variables
# Generated by 'wal'
wallpaper='/home/ciga/Pictures/desert-red-sky.png'

# Special
background='#07060c'
foreground='#a8a6b1'
cursor='#a8a6b1'

# Colors
color0='#07060c'
color1='#56345c'
color2='#7a2d4b'
color3='#5c4c58'
color4='#ae3c5f'
color5='#94818c'
color6='#948c94'
color7='#a8a6b1'
color8='#524d63'
color9='#56345c'
color10='#7a2d4b'
color11='#5c4c58'
color12='#ae3c5f'
color13='#94818c'
color14='#948c94'
color15='#a8a6b1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
