--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#282936"
foreground="#e9e9f4"
cursor="#e9e9f4"

-- Colors
color0="#282936"
color1="#ea51b2"
color2="#00f769"
color3="#ebff87"
color4="#62d6e8"
color5="#b45bcf"
color6="#a1efe4"
color7="#e9e9f4"
color8="#4d4f68"
color9="#ea51b2"
color10="#00f769"
color11="#ebff87"
color12="#62d6e8"
color13="#b45bcf"
color14="#a1efe4"
color15="#f7f7fb"
