--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ciga/Pictures/green_plant.jpg"

-- Special
background="#0f1314"
foreground="#a5bca9"
cursor="#a5bca9"

-- Colors
color0="#0f1314"
color1="#39664C"
color2="#35685C"
color3="#424A4A"
color4="#487354"
color5="#4E7964"
color6="#58853D"
color7="#a5bca9"
color8="#738376"
color9="#39664C"
color10="#35685C"
color11="#424A4A"
color12="#487354"
color13="#4E7964"
color14="#58853D"
color15="#a5bca9"
