# Shell variables
# Generated by 'wal'
wallpaper='/home/ciga/Pictures/green_plant.jpg'

# Special
background='#0f1314'
foreground='#a5bca9'
cursor='#a5bca9'

# Colors
color0='#0f1314'
color1='#39664C'
color2='#35685C'
color3='#424A4A'
color4='#487354'
color5='#4E7964'
color6='#58853D'
color7='#a5bca9'
color8='#738376'
color9='#39664C'
color10='#35685C'
color11='#424A4A'
color12='#487354'
color13='#4E7964'
color14='#58853D'
color15='#a5bca9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
