# Shell variables
# Generated by 'wal'
wallpaper='/home/ciga/Pictures/mac_night.png'

# Special
background='#0A0E16'
foreground='#cbc7bf'
cursor='#cbc7bf'

# Colors
color0='#0A0E16'
color1='#6F6659'
color2='#924F2F'
color3='#947357'
color4='#7E817B'
color5='#9C8973'
color6='#C7956C'
color7='#cbc7bf'
color8='#8e8b85'
color9='#6F6659'
color10='#924F2F'
color11='#947357'
color12='#7E817B'
color13='#9C8973'
color14='#C7956C'
color15='#cbc7bf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
